### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by fauzipadlaw** [tasyadas/ulang#1]
variable $link pada https://github.com/tasyadas/ulang/blame/master/main.php#L12 itu apa isinya?

SOLVED: ganti https://github.com/tasyadas/ulang/blame/master/main.php#L12 jadi include_once($link[$hal]);

**Comment by tasyadas** [comment]
buat ngelink ke php yang lain

**Comment by fauzipadlaw** [comment]
Saya coba, menunya lancar2 aja kok. 
Pas ngelink kemana yg gak bisa?

**Comment by fauzipadlaw** [comment]
coba upload database nya kesini, saya cobakan di komputer saya @tasyadas

**Comment by tasyadas** [comment]
ituloh yang ga bisa navigasi halaman yang ada didalem data pegawai

**Comment by tasyadas** [comment]
udah di upload itu dbnya. Tapi kok ga ada yang ext sql ya? bener ga sih itu yg diupload? wkwk @fauzipadlaw

**Comment by fauzipadlaw** [comment]
di export dulu databasenya di phpmyadmin

**Comment by fauzipadlaw** [comment]
tampil kok @tasyadas  
![image](https://user-images.githubusercontent.com/15975922/42964181-78565f32-8bc0-11e8-85fa-cb37681b535d.png)

**Comment by fauzipadlaw** [comment]
@tasyadas ganti https://github.com/tasyadas/ulang/blame/master/main.php#L12 jadi `include_once($link[$hal]);`

**Comment by tasyadas** [comment]
sorry kemaren ketiduran hehe

udah aku upload itu dbnya ya

**Comment by tasyadas** [comment]
coba deh dijalanin dbnya. nanti bakal ada navigasi diatas tabel buat ke halaman selanjutnya. nah kalo di pencet navigasinya malah balik ke home
