### ISSUE TITLE
navigasi

### ISSUE THREAD

**Issue by tasyadas** [tasyadas/ulang#2]
![image](https://user-images.githubusercontent.com/40492466/42995267-9e8f4c20-8c3a-11e8-8f73-9bc059fd7105.png)

jadi tuh angka 1 2 3 itu kalo di teken baliknya ke home karna https://github.com/tasyadas/ulang/blob/a0988c67b18b4f8fc276929ed6fc70b33d2e57d7/main.php#L15 elsenya ngarahin ke home. maunya tuh ke page selanjutnya

**Comment by fauzipadlaw** [comment]
fixed! masalahnya ada pada url pada link,
https://github.com/tasyadas/ulang/blob/859fe902c4553537b3e919c42da0cce0ae723016/list_peg.php#L44

**Comment by fauzipadlaw** [comment]
yg diatas masih kurang baik,
sepertinya ini lebih baik https://github.com/tasyadas/ulang/commit/448017c552709934ec5f0401aaed8c0743d06506
